name: Label Enhancements
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_enhancements:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Create ServiceNow Enhancement
        id: cServiceNowEnhancement
        if: |
          contains(github.event.issue.title, '[ENHANCEMENT]') 
            && !contains(github.event.issue.labels.*.name, 'ENCH')
        run: |
          $random = Get-Random -Maximum 9999 -Minimum 1000
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json

          Write-Host $("ENCH00"+$random)
          echo "SN_ENHANCEMENT=$("ENCH00"+$random)" >> $env:GITHUB_ENV
          echo "SN_STATE=$($github.issue.state)" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Label Enhancements
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "${{ env.SN_STATE }}, ${{ env.SN_ENHANCEMENT }}, triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
