name: Label Enhancements
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v1
      - name: new var
        id: Test
        run: |
          $random = Get-Random
          Write-Host $("ENCH"+$random)
          echo "SN_ENHANCEMENT=$("ENCH"+$random)" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "${{ env.SN_ENHANCEMENT }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
