name: Label Enhancements
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_enhancements:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Create ServiceNow Enhancement
        id: cServiceNowEnhancement
        if: contains(github.event.issue.labels.*.name, 'enhancement')
        run: |
          $random = Get-Random
          $events = $github.event | ConvertTo-Json -Depth 20
          Write-Host $events
          Write-Host $("ENCH"+$random)
          echo "SN_ENHANCEMENT=$("ENCH"+$random)" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Label Enhancements
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "${{ env.SN_ENHANCEMENT }}, triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
